services:
  pgsql:
    image: postgres:15-alpine
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'kknuinsaizu-pgsql:/var/lib/postgresql/data'
    networks:
      - kknuinsaizu
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s

  redis:
    image: redis:7-alpine
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'kknuinsaizu-redis:/data'
    networks:
      - kknuinsaizu
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

networks:
  kknuinsaizu:
    driver: bridge

volumes:
  kknuinsaizu-pgsql:
    driver: local
  kknuinsaizu-redis:
    driver: local
