import { useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { useMutation, useQuery } from '@tanstack/react-query'
import { ArrowLeft, Paperclip, Plus, RefreshCcw, Send } from 'lucide-react'
import { api } from '../../../shared/api/client'

export const LEAVE_ENDPOINT = '/student/izin'
type Rec = Record<string, unknown>
type Resp = Rec[] | { data?: Rec[]; items?: Rec[]; izin?: Rec[]; leaves?: Rec[] }
function arr(raw: Resp): Rec[] { if (Array.isArray(raw)) return raw; const r = raw as any; return r?.data || r?.items || r?.izin || r?.leaves || [] }
function pick(o: unknown, keys: string[]) { if (!o || typeof o !== 'object') return undefined; const r = o as Rec; for (const k of keys) if (r[k] !== undefined && r[k] !== null && r[k] !== '') return r[k]; return undefined }
function text(v: unknown, fb = '-') { return v === null || v === undefined || v === '' || typeof v === 'object' ? fb : String(v) }
function Badge({ value }: { value: unknown }) { const s = text(value, 'diajukan').toLowerCase(); const cls = s.includes('setuju') || s.includes('approved') ? 'bg-emerald-50 text-emerald-700' : s.includes('tolak') || s.includes('reject') ? 'bg-rose-50 text-rose-700' : 'bg-amber-50 text-amber-700'; return <span className={`rounded-full px-2 py-1 text-xs font-semibold ${cls}`}>{text(value, 'Diajukan')}</span> }

function LeaveForm({ onCancel, onDone }: { onCancel: () => void; onDone: () => void }) {
  const [jenis, setJenis] = useState('izin')
  const [mulai, setMulai] = useState('')
  const [selesai, setSelesai] = useState('')
  const [alasan, setAlasan] = useState('')
  const [file, setFile] = useState<File | null>(null)
  const m = useMutation({ mutationFn: async () => { const fd = new FormData(); fd.append('jenis', jenis); fd.append('tanggal_mulai', mulai); fd.append('tanggal_selesai', selesai); fd.append('alasan', alasan); if (file) fd.append('attachment', file); return api.post(LEAVE_ENDPOINT, fd, { headers: { 'Content-Type': 'multipart/form-data' } }) }, onSuccess: onDone })
  function submit(e: FormEvent) { e.preventDefault(); m.mutate() }
  return <section className="space-y-4"><div className="rounded-2xl border bg-white p-5 shadow-sm"><button onClick={onCancel} className="mb-3 inline-flex items-center gap-2 text-sm text-slate-600 hover:text-slate-900"><ArrowLeft className="h-4 w-4" /> Kembali</button><h2 className="text-lg font-semibold text-slate-800">Buat Izin</h2><p className="text-sm text-slate-500">POST {LEAVE_ENDPOINT}; multipart bila lampiran diisi. Payload: jenis, tanggal_mulai, tanggal_selesai, alasan, attachment.</p></div><form onSubmit={submit} className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm md:grid-cols-2"><label className="space-y-1 text-sm"><span className="font-medium text-slate-700">Jenis</span><select value={jenis} onChange={(e) => setJenis(e.target.value)} className="w-full rounded-xl border px-3 py-2"><option value="izin">Izin</option><option value="sakit">Sakit</option><option value="keluarga">Keluarga</option><option value="lainnya">Lainnya</option></select></label><label className="space-y-1 text-sm"><span className="font-medium text-slate-700">Lampiran</span><input type="file" onChange={(e) => setFile(e.target.files?.[0] ?? null)} className="w-full rounded-xl border px-3 py-2" /></label><label className="space-y-1 text-sm"><span className="font-medium text-slate-700">Tanggal mulai</span><input type="date" value={mulai} onChange={(e) => setMulai(e.target.value)} required className="w-full rounded-xl border px-3 py-2" /></label><label className="space-y-1 text-sm"><span className="font-medium text-slate-700">Tanggal selesai</span><input type="date" value={selesai} onChange={(e) => setSelesai(e.target.value)} required className="w-full rounded-xl border px-3 py-2" /></label><label className="space-y-1 text-sm md:col-span-2"><span className="font-medium text-slate-700">Alasan</span><textarea value={alasan} onChange={(e) => setAlasan(e.target.value)} required rows={5} className="w-full rounded-xl border px-3 py-2" /></label>{m.isError && <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700 md:col-span-2">Gagal mengirim izin.</div>}<div className="flex justify-end gap-2 md:col-span-2"><button type="button" onClick={onCancel} className="rounded-xl border px-4 py-2 text-sm hover:bg-slate-50">Batal</button><button disabled={m.isPending} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-800 disabled:opacity-60"><Send className="h-4 w-4" /> Kirim</button></div></form></section>
}

export function LeavePage() {
  const path = window.location.pathname
  const [mode, setMode] = useState(path.endsWith('/buat') ? 'create' : 'list')
  const q = useQuery({ queryKey: ['student-leave'], queryFn: () => api.get<Resp>(LEAVE_ENDPOINT).then((r) => arr(r.data)), retry: false })
  const rows = useMemo(() => q.data ?? [], [q.data])
  const goList = () => { window.history.pushState(null, '', '/mahasiswa/izin'); setMode('list') }
  if (mode === 'create') return <LeaveForm onCancel={goList} onDone={() => { goList(); void q.refetch() }} />
  return <section className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border bg-white p-5 shadow-sm"><div><h2 className="text-lg font-semibold text-slate-800">Izin Mahasiswa</h2><p className="text-sm text-slate-500">Endpoint: {LEAVE_ENDPOINT}</p></div><div className="flex gap-2"><button onClick={() => q.refetch()} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm hover:bg-slate-50"><RefreshCcw className="h-4 w-4" /> Refresh</button><button onClick={() => { window.history.pushState(null, '', '/mahasiswa/izin/buat'); setMode('create') }} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-3 py-2 text-sm font-medium text-white hover:bg-emerald-800"><Plus className="h-4 w-4" /> Buat</button></div></div>{q.isLoading && <div className="rounded-2xl border bg-white p-5 text-slate-500">Memuat izin...</div>}{q.isError && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-800">Gagal membaca izin.</div>}{!q.isLoading && !q.isError && rows.length === 0 && <div className="rounded-2xl border bg-white p-5 text-slate-500">Belum ada izin.</div>}<div className="grid gap-4 lg:grid-cols-2">{rows.map((x, i) => { const file = text(pick(x, ['attachment_url', 'lampiran', 'file_url', 'attachment']), ''); return <article key={text(pick(x, ['id']), String(i))} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-3 flex items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-800">{text(pick(x, ['jenis', 'type']), 'Izin')}</h3><p className="text-sm text-slate-500">{text(pick(x, ['tanggal_mulai', 'start_date', 'mulai']))} – {text(pick(x, ['tanggal_selesai', 'end_date', 'selesai']))}</p></div><Badge value={pick(x, ['status', 'approval_status'])} /></div><p className="text-sm text-slate-600">{text(pick(x, ['alasan', 'reason', 'keterangan', 'description']))}</p>{file && <a href={file} target="_blank" className="mt-3 inline-flex items-center gap-2 text-sm font-medium text-emerald-700"><Paperclip className="h-4 w-4" /> Lampiran</a>}</article> })}</div></section>
}
