# FreeBSD setup
# pkg install py39-supervisor
# sysrc supervisord_enable="YES"
# service supervisord start
# supervisorctl reread && supervisorctl update

[unix_http_server]
file=/var/run/supervisor.sock

[supervisord]
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[program:sibermas-worker]
command=php /path/to/apps/api/artisan queue:work redis --sleep=3 --tries=3 --max-time=3600
directory=/path/to/apps/api
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/var/log/sibermas-worker.log
stderr_logfile=/var/log/sibermas-worker-error.log

[program:sibermas-horizon]
command=php /path/to/apps/api/artisan horizon
directory=/path/to/apps/api
autostart=true
autorestart=true
stdout_logfile=/var/log/sibermas-horizon.log
stderr_logfile=/var/log/sibermas-horizon-error.log
